### PR TITLE
Adds light theme.

### PR DESCRIPTION
**Pull request by samdixon**
Hello. I like the project and really like the color scheme. What I miss the most about Sublime is the default color scheme with the light background/sidebars. I have created an additional theme called 'Sublime Monokai Theme Light'. This uses the same base Monokai theme, but changes the border (and random things) to match the light sublime thing.

If possible, could you create a development branch so we may work on this project together? Deny this pull request and I can then re-submit it to the development branch so you can have a look.

Let me know, thanks for the project.

### CODE REVIEW

**Comment by samdixon** [comment]
There is a lot incomplete about this. I plan on cleaning it up at a later point, just want to make sure you are on board with collaboration.

**Comment by maximetinu** [comment]
Hi @zeusofjuice and thanks so much for the contribution! I like this approach to sublime's theme since it also reproduces that light sidebar of it which I forgot.
I will merge your theme to a new development branch I created. You can continue working on it there by more PR's if you want, and as soon as you think it's ready to be released I will merge it to the master and publish to the vs marketplace (in my opinion it's already).

Also, sorry that took so long, I've being busy and I would also like to correct some bugs in the original theme.

BTW, I wasn't been able to enable the light theme until I realized that the package.json was referencing the wrong theme path. It's referencing to "./themes/sublime-monokai-theme-light.json" and it has to be "./themes/sublime-monokai-color-theme-light.json". I will change it after merge.

Thanks again!

**Comment by samdixon** [comment]
Hey Miguel - All the notifications come to my secondary email so I rarely
check them.... so apologies for the delay on my end as well haha. I'll work
on updating that and seeing if we can't get something pushed to the master
branch this weekend :)

- Sam

**Comment by maximetinu** [comment]
Okey, great! And don't worry about time, unfortunately I don't have too much to spend on this either, but hey, great things take time ;)

**Comment by samdixon** [comment]
I think we are good to merge. I haven't made any changes on my end. 
Somewhat forgot about this :). I have been using it in my daily use and 
haven't discovered too many issues. I may make some updates at some 
point. Please keep a development branch open in the future for me to 
pull against.


Thanks Again!


Sam

**Pull request merged**
